### ISSUE TITLE
prev final argument order?

### ISSUE THREAD

**Issue by jamesdbrock** [jeslie0/mkSpagoDerivation#4]
Should this say

```nix
mkSpagoDerivationBuilder = prev: final: 
```
?

https://github.com/jeslie0/mkSpagoDerivation/blob/d8c082f8a161a1852dd5276bf4ab0de7891f5157/flake.nix#L48

Maybe here too?

https://github.com/jeslie0/mkSpagoDerivation/blob/d8c082f8a161a1852dd5276bf4ab0de7891f5157/flake.nix#L62

**Comment by jeslie0** [comment]
My understanding is that an overlay is a function which takes takes the final version of nixpkgs (with all overlays applied), then takes the copy of nixpkgs before this overlay is applied. Based on that, I think my function arguments are ordered correctly. What is your reason for thinking they should be ordered `prev`, `final`?

Looking at the code, I think that I can remove the `final` argument from mkSpagoDerivationBuilder, since it isn't used. It will also make clear what should be considered an overlay and what is just a method to build a package!
